#!/bin/bash

if true; then
	pkill -x waybar
	waybar \
		-c ~/.config/waybar/normal/config.jsonc \
		-s ~/.config/waybar/normal/style.css
    killall dunst
    notify-send --urgency=low --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9000
    notify-send --urgency=normal --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9001
    notify-send --urgency=critical --transient "Bar refreshed!" "Alt+Shift+R to refresh!" -r 9002 -t 4000
	# hyprctl reload
fi
