#!/bin/bash


# ---- Config ----
choice=$1
path="$HOME/Pictures/Screenshots"
tempdir="/tmp/screenshots"
mkdir -p "$tempdir"
file="$(mktemp -p "$tempdir" "XXXXXX.png")"
format=$(date +'%Y.%m.%d_%A[%H:%M:%S].png')


# ---- Mission Starto -----
if [ ! -d "$path" ]; then
  mkdir -p $HOME/Pictures/Screenshots
fi

screen() {
	grim "$file" || exit
	cp -rf "$file" "$HOME/Pictures/Screenshots/${format}"
	wl-copy -t image/png < "$file"
	if [ $? -eq 0 ]; then
		notify-send --urgency=low --transient -i "$file" "📷 Screenshot Captured!" "Image copied to clipboard and saved to $file" -r 9005 -t 2000
	else
		notify-send --urgency=low --transient "Failed to screenshot!" -r 9005 -t 2000
	fi
}

dwl() {
	read -r PID
	read -r TITLE
	read -r APPID
	read -r TAGS
	read -r GEOMETRY
	[ -n "$GEOMETRY" ] || exit 1
}

window() {
	dwl
	grim -g "$GEOMETRY" "$file" || exit
	cp -rf "$file" "$HOME/Pictures/Screenshots/Region-${format}"
	wl-copy -t image/png < "$file"
	if [ $? -eq 0 ]; then
		notify-send --urgency=low --transient -i "$file" "📷 Windowshot Captured!" "Image copied to clipboard and saved to $file" -r 9005 -t 2000
	else
		notify-send --urgency=low --transient "❗There's no Active Window!" -r 9005 -t 2000
	fi
}

case $choice in
	scr) screen ;;
	win) window ;;
	screen) screen ;;
	window) window ;;
esac
