#!/bin/bash

tempat="/tmp/blurbgstatus"
printf "" > $tempat
while true; do
    running="$(cat $tempat)"
    id=$(ps -ef | grep '[w]aybar -c' | grep blurbg | awk '{print $2}')
    window="$(hyprctl activeworkspace | grep windows: | awk '{print $2}')"
    if [ "$window" -gt 0 ]; then
        if [ ! "$running" = 1 ]; then
            kill $id
            printf 1 > $tempat
            waybar -c $HOME/.config/waybar/blurbg/config.jsonc -s $HOME/.config/waybar/blurbg/style.css &
        fi
    fi
    if [ ! "$window" -gt 0 ]; then
        if [ ! "$running" = 0 ]; then
            printf 0 > $tempat
            kill $id
        fi
    fi
    sleep 1
done

