#!/bin/bash
read -r PID
read -r TITLE
read -r APPID
read -r TAGS
read -r GEOMETRY
[ -n "$GEOMETRY" ] || exit 1

# ---- Config ----
tempdir="/tmp/screenshots"
mkdir -p "$tempdir"
file="$(mktemp -p "$tempdir" "XXXXXX.png")"
choice=$1
format=$(date +'%Y.%m.%d_%A[%H:%M:%S].png')
path="$HOME/Pictures/Screenshots"

# ---- Mission Starto -----
if [ ! -d "$path" ]; then
  mkdir -p $HOME/Pictures/Screenshots
fi

# grim -g "$activewindow1 $activewindow2" $HOME/Pictures/Screenshots/Region-${format}
grim -g "$GEOMETRY" "$file" || exit
cp -rf "$file" "$HOME/Pictures/Screenshots/Region-${format}"
wl-copy -t image/png < "$file"
if [ $? -eq 0 ]; then
	notify-send --urgency=low --transient -i "$file" "📷 Windowshot Captured!" "Image copied to clipboard and saved to $file" -r 9005 -t 2000
else
	notify-send --urgency=low --transient "❗There's no Active Window!" -r 9005 -t 2000
fi
