#!/bin/bash


# ---- Environments ----
export PATH=$HOME/bin:$HOME/.local/bin:$HOME/.config/bin:/usr/local/bin:$PATH
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_SESSION_TYPE=wayland
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="google-chrome-stable"
export VISUAL="${EDITOR}"
export WLR_NO_HARDWARE_CURSORS=1
export ACCESSIBILITY_ENABLED=1
export QT_ACCESSIBILITY=1
# export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
# Evals
eval "$(starship init bash)"


# ---- Settings ----
[[ $- != *i* ]] && return
HISTSIZE=5000
HISTFILE=$HOME/.config/bashist
SAVEHIST=$HISTSIZE
HISTDUP=erase


# ---- Alias ----
alias cat='bat'
alias ls='eza --color=always --git --no-filesize --icons=always --no-time --no-user --no-permissions -a'
alias grep='grep --color=auto'
alias vi='nvim'
alias neovim='nvim'
alias bf='bunnyfetch'
alias ff="fastfetch"
alias boottime='systemd-analyze'
alias grep='grep --color=auto'
alias bashrc='nvim $HOME/.config/bashrc'
alias init.lua='nvim $HOME/.config/nvim/init.lua'
alias kanata-reload='sudo systemctl stop kanata; sudo systemctl start kanata; systemctl status kanata'
alias publicip='curl https://ipinfo.io/ip'
function y(){
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
alias yazi=y
alias init.plugins=init.plugin

alias mem='free --mega'
alias memory='free --mega'
alias disk='echo -e "Filesystem      Size  Used Avail Use% Mounted on"; df -h | grep /boot; df -h | grep /home'

# PROMPT_COMMAND='PS1_CMD1=$()'; PS1='\W\n; ${PS1_CMD1}'
# checkifitfirstornot=$(hyprctl clients | grep -c "class: kitty")
# if [ "$checkifitfirstornot" -lt 4 ]; then
#     bunnyfetch
# fi
bunnyfetch
