#!/bin/bash


# ---- Environments ----
export PATH=$HOME/bin:$HOME/.local/bin:$HOME/.config/bin:/usr/local/bin:$PATH
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_SESSION_TYPE=wayland
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="google-chrome-stable"
export VISUAL="${EDITOR}"
export WLR_NO_HARDWARE_CURSORS=1
export ACCESSIBILITY_ENABLED=1
export QT_ACCESSIBILITY=1
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
# Evals
eval "$(starship init bash)"


# ---- Settings ----
[[ $- != *i* ]] && return
HISTSIZE=5000
HISTFILE=$HOME/.config/bashist
SAVEHIST=$HISTSIZE
HISTDUP=erase


# ---- Alias ----
# alias cat='bat'
# alias ls='eza --color=always --git --no-filesize --icons=always --no-time --no-user --no-permissions -a'
alias grep='grep --color=auto'
alias v='$EDITOR'
alias vi='$EDITOR'
alias vim='$EDITOR'
alias nvim='$EDITOR'
alias neovim='$EDITOR'
alias bf='bunnyfetch'
alias ff="fastfetch"
alias boottime='systemd-analyze'
alias bashrc='$EDITOR $HOME/.config/bashrc'
alias init.lua='$EDITOR $HOME/.config/nvim/init.lua'

alias mem='free --mega'
alias memory='free --mega'
alias disk='echo -e "Filesystem      Size  Used Avail Use% Mounted on"; df -h | grep /boot; df -h | grep /home'

function lf (){
	blue="\033[1;34m"
	black="\033[0;30m"
	none="\033[0m"
	for isi in $(ls -la $(pwd) | awk 'NR >= 4 {print $9}'); do
		if [ -d "$isi" ]; then
			echo -e "${black}-- ${blue} ${isi}"
		elif [ -f "$isi" ]; then
			echo -e "${black}-- ${none} ${isi}"
		else
			echo $isi
		fi
	done
}

bunnyfetch
