-- Mini Setup
require("mini.icons").setup()
require("mini.bracketed").setup()
require("mini.indentscope").setup()
require("mini.notify").setup()
require("mini.comment").setup()
require("mini.move").setup()
require("mini.splitjoin").setup()
require("mini.tabline").setup()
require("mini.trailspace").setup()
require("mini.surround").setup()
